package com.hbtl.beans;

/**
 * Created by 亚飞 on 2015-10-13.
 */
public class CrossIcReaderInfoBus {
    // 刷卡验证方式...
    public String readWay;// [NFC:NFC模块]...
    // 刷卡状态码...
    public int readCode;
    // 卡码认证方式...
    public String verifyWay = "";// [osp:服务商|msp:服务网]...
    public long verifyTs = 0;// 认证唯一编码-过期返回会作废...
    public String msIcNo = null;// ms 接口返回的身份证编号...
}
