/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hbtl_utils_EktCso */

#ifndef _Included_com_hbtl_utils_EktCso
#define _Included_com_hbtl_utils_EktCso
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hbtl_utils_EktCso
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hbtl_utils_EktCso_getString(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
